import './globals.css'
import { Inter } from 'next/font/google'
import Sidebar from "./Sidebar";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <div className="grid grid-cols-sidebar"> {/* Apply the grid class here */}
        <Sidebar/>
        <div className="main-content"> {/* Add a container for the main content */}
          {children}
          {/*<body className={inter.className}>{children}</body> */}
        </div>
      </div>
    </html>
  )
}