import './globals.css';
import '../styles/index.css';
import { Inter } from 'next/font/google';
import Sidebar from "./Sidebar";

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        {/* Add any necessary head elements here */}
      </head>
      <body>
          {/* Apply the grid class here */}
          <div className="main-content">
            {/* Add a container for the main content */}
            <Sidebar />
            <div className="p-4 sm:ml-64">
                {children}
            </div>
          </div>
      </body>
    </html>
  );
}
